# Generated by Django 4.0.4 on 2022-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('AccId', models.AutoField(primary_key=True, serialize=False)),
                ('AccName', models.CharField(max_length=500)),
            ],
        ),
    ]
